#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
. ${OPENSHIFT_DATA_DIR}node.sh
# Need to clean node-gyp up as somehow it got corrupt after a few build
rm -rf ${OPENSHIFT_TMP_DIR}/.node-gyp
cd ${OPENSHIFT_REPO_DIR}
npm install
# To keep node running if crashed
npm install supervisor -g
